apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: dhirunittest 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: dhirunittest 
    spec:
      containers:
        - name: dhirunittest 
          image: azdevops.azurecr.io/dhirunittest
          ports:
          - containerPort: 80